name = input("What's your name? ")
age = int(input("And how old you? "))
weigh = float(input("Okay, last question. How many pounds do you weigh? "))
print("\n")
print("Did you know that you're just", age // 7, "in dog years?")
print("But your're also over", age * 365 * 24 * 60 * 60, "seconds old.\n")
print("If a small child were trying to get your attention, your name would become:")
print(name+name+name+name+name)
print("\n")
print("Did you know that on the moon you would weigh only", weigh / 6, "pounds?")
print("But on the sun, you'd weigh", weigh * 27.3, "<but, ah... not for long>.\n")
