print("\t\t\tTrust Fund Buddy\n")
print("Totals your monthly spending so that your trust fund doesn't run out")
print("<and you're foreced to get a real job>.")
print("\nPlease enter the requested, monthly costs. Since you're rich, ignore pennies")
print("and use only dollar amounts.\n\n")
tune = int(input("Lamborghini Tune-Ups: "))
apartment = int(input("Manhattan Apartment: "))
rental = int(input("Private Jet Rental: "))
gifs = int(input("Gifs: "))
dinning = int(input("Dinning Out: "))
staff = int(input("Staff <butlers, chef, driver, assistant>: "))
person = int(input("Personal Guru and Coach: "))
game = int(input("Computer Games: "))
print("\nGrand Total:   ",tune+apartment+rental+gifs+dinning+staff+person+game)
print("\n")
